- name:  Iptables Input Rule
  hosts: all  # Use sudo for privilege escalation
  tasks:
    - name: Backup command

      shell: cp -r /etc/sysconfig/iptables /etc/sysconfig/iptables.BK
        
    - name: Copy the Default rule to servers
      copy:
        src: /root/iptables_automation/rule/input_edit
        dest: /etc/sysconfig/input_edit
    
    - name: Add New IP table rules
      shell: awk 'FNR==NR {exclude[$0]; next} {  if ($0 ~ /-A INPUT -j LOG --log-prefix/) { while ((getline line < "/etc/sysconfig/input_edit") > 0) print line; }  if (!($0 in exclude)) print; }' /etc/sysconfig/input_edit /etc/sysconfig/iptables > /etc/sysconfig/temp && mv /etc/sysconfig/temp /etc/sysconfig/iptables


    - name: Restart IP tables
      shell: sudo systemctl reload iptables
      
    - name: Check if iptables service is runningclea
      command: systemctl is-active iptables
      register: iptables_status
      failed_when: false 
      ignore_errors: true 

    - name: Reload iptables if it is active
      become: true		
      command: systemctl reload iptables
      when: iptables_status.stdout == "active"

    - name: Log servers with iptables inactive
      delegate_to: localhost
      lineinfile:
        path: /root/iptables_automation/iptables_inactive.log
        line: "{{ inventory_hostname }} ({{ hostvars[inventory_hostname]['ansible_host'] }}): iptables is inactive"
        create: yes  
        insertbefore: EOF
      when: iptables_status.stdout == "inactive"
