- name: Back Up IPtables 
  hosts: servers
  tasks:
   

    - name: Check if iptables service is running
      command: systemctl is-active iptables
      register: iptables_status
      failed_when: false 
      ignore_errors: true 


    - name: Reload iptables if it is active
      become: true		
      command: systemctl reload iptables
      when: iptables_status.stdout == "active"

    - name: Log servers with iptables inactive
      delegate_to: localhost
      lineinfile:
        path: /root/iptables_automation/iptables_inactive.log
        line: "{{ inventory_hostname }} ({{ hostvars[inventory_hostname]['ansible_host'] }}): iptables is inactive"
        create: yes  
        insertbefore: EOF
      when: iptables_status.stdout == "inactive"

