- name: Iptable for output rule
  hosts: servers
  tasks:
    - name: Backup command
      ansible.builtin.command:
        cmd: cp -r /etc/sysconfig/iptables /etc/sysconfig/iptables.BK
        
    - name: Copy the Default rule to servers
      copy:
        src: /root/iptables_automation/rule/output
        dest: /etc/sysconfig/output
    
    - name: Set Up Iptables
      shell: awk 'FNR==NR {exclude[$0]; next} {  if ($0 ~ /-A OUTPUT -j LOG --log-prefix/) { while ((getline line < "/etc/sysconfig/output") > 0) print line; }  if (!($0 in exclude)) print; }' /etc/sysconfig/output /etc/sysconfig/iptables > /etc/sysconfig/temp && mv /etc/sysconfig/temp /etc/sysconfig/iptables

    - name: start iptables 
      command: sudo  systemctl start iptables
    
    - name: Reload iptables 
      command: sudo  systemctl reload iptables

    - name: Check if iptables service is running
      command: sudo systemctl is-active iptables
      register: iptables_status
      failed_when: false 
      ignore_errors: true 


    - name: Reload iptables if it is active
      command: sudo systemctl reload iptables
      when: iptables_status.stdout == "active"

    - name: Log servers with iptables inactive
      delegate_to: localhost
      lineinfile:
        path: /root/iptables_automation/iptables_inactive.log
        line: "{{ inventory_hostname }} ({{ hostvars[inventory_hostname]['ansible_host'] }}): iptables is inactive"
        create: yes  
        insertbefore: EOF
      when: iptables_status.stdout == "inactive"