- name: Iptable for output rule
  hosts: servers
  become: yes  # Use sudo for privilege escalation
  tasks:
    - name: Backup command
      ansible.builtin.command:
        cmd: cp -r /etc/sysconfig/iptables /etc/sysconfig/iptables.BK
        
    - name: Copy the Default rule to servers
      copy:
        src: /root/iptables_automation/rule/output
        dest: /etc/sysconfig/output
    
    - name: Set Up Iptables
      shell: grep -Fxv -f /etc/sysconfig/input_edit /etc/sysconfig/iptables | sed -e "$(($(wc -l < /etc/sysconfig/iptables) - 4))r /etc/sysconfig/output" /etc/sysconfig/iptables > /etc/sysconfig/temp && mv /etc/sysconfig/temp /etc/sysconfig/iptables -f

    - name: Create IP table directory
      file:
        path: /root/iptables_automation
        state: directory
        mode: '0755'

    - name: Check if iptables service is running
      command: systemctl is-active iptables
      register: iptables_status
      failed_when: false 
      ignore_errors: true 


    - name: Reload iptables if it is active
      become: true		
      command: systemctl reload iptables
      when: iptables_status.stdout == "active"

    - name: Log servers with iptables inactive
      delegate_to: localhost
      lineinfile:
        path: /root/iptables_automation/iptables_inactive.log
        line: "{{ inventory_hostname }} ({{ hostvars[inventory_hostname]['ansible_host'] }}): iptables is inactive"
        create: yes  
        insertbefore: EOF
      when: iptables_status.stdout == "inactive"