- name:  Iptables Input Rule
  hosts: all  # Use sudo for privilege escalation
  tasks:
    - name: Backup Iptables
      shell: cp -r /etc/sysconfig/iptables /etc/sysconfig/iptables.BK
        
    - name: Copy Update rule to servers
      copy:
        src: /root/iptables_automation/rule/update_rule
        dest: /etc/sysconfig/update_rule

    - name: Upload the bash shell script for data analysis and edit
      copy:
        src: /root/iptables_automation/scripts/updates.sh
        dest: /etc/sysconfig/updates.sh

    - name: Add New IP table rules
      shell: bash /etc/sysconfig/updates.sh

    - name: Reload IP tables
      shell: sudo systemctl reload iptables
      
    - name: Check if iptables service is running
      command: sudo systemctl is-active iptables
      register: iptables_status
      failed_when: false 
      ignore_errors: true 

    - name: Reload iptables if it is active	
      command: sudo systemctl reload iptables
      when: iptables_status.stdout == "active"

    - name: Check for iptables cmd or software 
      command: which iptables
      register: iptables_check
      ignore_errors: yes
    
    - name: Log for iptable checking 
      delegate_to: localhost
      lineinfile:
        path: /root/iptables_automation/iptables.log
        line: "({{ hostvars[inventory_hostname]['ansible_host'] }}): need to install iptables"
        create: yes
        insertbefore: EOF
      when: iptables_check.rc != 0

    - name: Log servers with iptables inactive
      delegate_to: localhost
      lineinfile:
        path: /root/iptables_automation/iptables_inactive.log
        line: "{{ inventory_hostname }} ({{ hostvars[inventory_hostname]['ansible_host'] }}): iptables is inactive"
        create: yes  
        insertbefore: EOF
      when: iptables_status.stdout == "inactive"
